light:
  - platform: hue
    host: 192.168.1.40

  - platform: rfxtrx
    automatic_add: True

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A118TT41-if00-port0
  
sensor:
  
  - platform: rfxtrx
    automatic_add: True
